user_security:
    resource: @LichessUserBundle/Resources/config/routing/security.yml
user_profile:
    resource: @FOSUserBundle/Resources/config/routing/profile.yml
user_registration:
    resource: @FOSUserBundle/Resources/config/routing/registration.yml
user_online:
    resource: @LichessUserBundle/Resources/config/routing/online.yml
user_stats:
    resource: @LichessUserBundle/Resources/config/routing/stats.yml

lichess:
    resource: @LichessBundle/Resources/config/routing.yml
lichess_hook:
    resource: @LichessOpeningBundle/Resources/config/routing.yml
lichess_hook_sync:
    resource: @LichessOpeningBundle/Resources/config/routing_sync.yml
lichess_sync:
    resource: @LichessBundle/Resources/config/routing_sync.yml
lichess_translation:
    resource: @LichessTranslationBundle/Resources/config/routing.yml
    prefix: /translation

forum:
    resource: @LichessForumBundle/Resources/config/routing.yml
    prefix: /forum
forum_category:
    resource: @HerzultForumBundle/Resources/config/routing/category.xml
    prefix: /forum
forum_topic:
    resource: @HerzultForumBundle/Resources/config/routing/topic.xml
    prefix: /forum
forum_post:
    resource: @HerzultForumBundle/Resources/config/routing/post.xml
    prefix: /forum

ornicar_message:
    resource: @OrnicarMessageBundle/Resources/config/routing.xml
    prefix: /inbox
