imports:
    - { resource: config.yml }

app.config:
    router: { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler:
        only_exceptions: false

webprofiler.config:
    toolbar: true
    intercept_redirects: false

zend.config:
    logger:
        priority: notice
        path:     %kernel.logs_dir%/%kernel.environment%.log

twig.config:
    auto_reload: true
