parameters:
    kernel.include_core_classes: false

kernel.config:
    charset:             UTF-8
    error_handler_level: null

kernel.session:
    lifetime: 2592000 # one month 

web.config:
    validation:
        enabled: true
    router: { resource: "%kernel.root_dir%/config/routing.yml" }

web.templating:
    escaping: false

lichess.config: ~
