_main:
    resource: routing.yml

_profiler:
    resource: @WebProfilerBundle/Resources/config/routing/profiler.xml
    prefix:   /_profiler

_wdt:
    resource: @WebProfilerBundle/Resources/config/routing/wdt.xml
    prefix:   /_wdt
